In [15]:
import numpy as np
from sympy import *

Общая часть

In [ ]:
A = np.array([[-7,4,0],  [0,-1,0],  [-1,5,7]])
A

array([[-7,  4,  0],
       [ 0, -1,  0],
       [-1,  5,  7]])

In [ ]:
E = np.eye(3)
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [ ]:
A = np.array ([[-7,4,0], [0,-1,0],  [-1,5,7]])
A[0,1]

4

In [ ]:
A[:,1:3]

array([[ 4,  0],
       [-1,  0],
       [ 5,  7]])

In [ ]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
E = np.eye(3)
A-E

array([[0., 2., 3.],
       [4., 4., 6.],
       [7., 8., 8.]])

In [ ]:
3*A

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [ ]:
А = np.array([[1,2,3], [4,5,6]])
В = np.array([[0,0,0], [2,2,2]])
А*В

array([[ 0,  0,  0],
       [ 8, 10, 12]])

In [ ]:
B = np.array([[1,0],[0,-2],[2,1]])
B.T

array([[ 1,  0,  2],
       [ 0, -2,  1]])

In [ ]:
A = np.array([[-7,4,0],[0,-1,0],[-1,5,7]])
В = np.array([[1,0],[0,-2],[2,1]])
F = А@В
F

array([[ 7, -1],
       [16, -4]])

In [ ]:
F = np.dot(A,B)
F

array([[-7, -8],
       [ 0,  2],
       [13, -3]])

In [ ]:
F = np.matmul(A,B)
F

array([[-7, -8],
       [ 0,  2],
       [13, -3]])

In [ ]:
C = np.array([[7,-3],[1,2]])
np.linalg.det(C)

17.0

In [ ]:
np.linalg.inv(C)

array([[ 0.11764706,  0.17647059],
       [-0.05882353,  0.41176471]])

In [ ]:
np.linalg.matrix_rank(A)

3

In [ ]:
a = Matrix([[1,2,3], [0,-1, 1]])
a

Matrix([
[1,  2, 3],
[0, -1, 1]])

In [ ]:
x,y,z = symbols('x у z')
v = Matrix([[1,x],[y,z]])
v

Matrix([
[1, x],
[у, z]])

In [ ]:
eye(3)

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [ ]:
zeros(2,3)

Matrix([
[0, 0, 0],
[0, 0, 0]])

In [ ]:
ones(3,2)

Matrix([
[1, 1],
[1, 1],
[1, 1]])

In [ ]:
diag(1,5,-2)

Matrix([
[1, 0,  0],
[0, 5,  0],
[0, 0, -2]])

In [ ]:
diag(-1, ones(2, 2), Matrix([5, 7, 5]))

Matrix([
[-1, 0, 0, 0],
[ 0, 1, 1, 0],
[ 0, 1, 1, 0],
[ 0, 0, 0, 5],
[ 0, 0, 0, 7],
[ 0, 0, 0, 5]])

In [ ]:
W = Matrix([[1,2,3]])
W

Matrix([[1, 2, 3]])

In [ ]:
W = Matrix([[1],[2],[3]])
W

Matrix([
[1],
[2],
[3]])

In [ ]:
A = Matrix([[1,2,3], [0,-1, 1]])
A.shape

(2, 3)

In [ ]:
a11, a12, a13, a21, a22, a23, a31, a32, a33 = symbols('a11 a12 a13 a21 a22 a23 a31 a32 a33 ')
A = Matrix([[a11, a12, a13],[a21, a22, a23],[a31, a32, a33]])
A

Matrix([
[a11, a12, a13],
[a21, a22, a23],
[a31, a32, a33]])

In [ ]:
A[2,0]

a31

In [ ]:
A[:, 1:2]

Matrix([
[a12],
[a22],
[a32]])

In [ ]:
A.row(0)

Matrix([[a11, a12, a13]])

In [ ]:
A.col(1)

Matrix([
[a12],
[a22],
[a32]])

In [ ]:
A.row_del(0)
A

Matrix([
[a21, a22, a23],
[a31, a32, a33]])

In [ ]:
A.col_del(1)
A

Matrix([
[a21, a23],
[a31, a33]])

In [ ]:
B = Matrix([[1,2,3],  [7,8,9]])
I = B.row_insert(1, Matrix([[4,5,6]]))
I

Matrix([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [ ]:
D = I.col_insert(3,Matrix([4,1,6]))
D

Matrix([
[1, 2, 3, 4],
[4, 5, 6, 1],
[7, 8, 9, 6]])

In [ ]:
V = Matrix([[1,x],[y,z]])
V*V

Matrix([
[x*у + 1,    x*z + x],
[z*у + у, x*у + z**2]])

In [ ]:
B.T

Matrix([
[1, 7],
[2, 8],
[3, 9]])

In [ ]:
D = Matrix([[0,1],[1,0]])
det(D)

-1

In [ ]:
D.inv()

Matrix([
[0, 1],
[1, 0]])

In [ ]:
A = Matrix([[1,8,3],[4,5,6],[7,8,9]])
A**-1

Matrix([
[-1/12, -4/3, 11/12],
[  1/6, -1/3,   1/6],
[-1/12,  4/3,  -3/4]])

In [ ]:
A = Matrix([[1, -1, 2],[2, -2, 4],[-1, 1, 2]])
A.rank()

2

Задание 1

In [16]:
givenMat = Matrix([[1,3,4,5,0],[4,-1,0,1,2],[3,2,5,5,3],[-2,0,1,-1,1],[4,6,7,11,-1]])
givenMat.rank()

3

Задание 2

In [ ]:
givenMat = Matrix([[1,3,4],[4,-1,0],[3,2,5],[-2,0,1],[4,6,7]])
givenMat.T
givenMat.columnspace()

[Matrix([
 [ 1],
 [ 4],
 [ 3],
 [-2],
 [ 4]]),
 Matrix([
 [ 3],
 [-1],
 [ 2],
 [ 0],
 [ 6]]),
 Matrix([
 [4],
 [0],
 [5],
 [1],
 [7]])]

Задание 3

In [91]:
givenMat = Matrix([[1, 2,0,9],[-3,7, 11,5],[-9,4,25,84],[3,12,-5,58]])
givenMat.minorEntry(2,1)

501

Задание 4

In [24]:
givenMat.cofactor_matrix()


Matrix([
[20026, -2754,  7146,  150],
[ -860,  1600,   308, -260],
[ -177,  -501,   211,  131],
[-2777,  1015, -1441,   83]])

Задание 5

In [33]:
row = [0,2]
colum = [2,3]
det(givenMat.extract(row,colum))

-225

Задание 6

In [73]:
givenMat = Matrix([[1,3,2,4,5],[0,0,-1,2,7],[3,9,6,12,15],[5,15,9,26,22],[1,3,1,10,2]])
reduced_mat, pivots = givenMat.rref()
det(reduced_mat)

Minor = Matrix()
for i in range(reduced_mat.rows):
    row = reduced_mat.row(i)
    position = 0
    flag = 0
    for j in range(reduced_mat.cols):
        if row[j] != 0:
          flag = 1
          break
    if flag == 1:
        Minor = Minor.row_insert(position, row)
        position += 1


print("Базисные строки:")
for row in Minor.tolist():
    print(row)

print("\nБазисные столбцы:")
for row in Minor.T.tolist():
    print(row)

print("\nБазисный минор:\n")
Minor


Базисные строки:
[0, 0, 0, 1, -5/2]
[0, 0, 1, 0, -12]
[1, 3, 0, 0, 39]

Базисные столбцы:
[0, 0, 1]
[0, 0, 3]
[0, 1, 0]
[1, 0, 0]
[-5/2, -12, 39]

Базисный минор:



Matrix([
[0, 0, 0, 1, -5/2],
[0, 0, 1, 0,  -12],
[1, 3, 0, 0,   39]])

СЛАУ

In [81]:
A = np.array([[3,2,0],
              [1,-1,0],
              [0,5,1]])
b = np.array([[2],[4],[-1]])
u = np.linalg.solve(A,b)
u

array([[ 2.],
       [-2.],
       [ 9.]])

In [83]:
A = Matrix([[3,2,0],
            [1,-1,0],
            [0,5,1]])
b = Matrix([[2],[4],[-1]])
x = A**-1 * b
x

Matrix([
[ 2],
[-2],
[ 9]])

In [84]:
F = Matrix([[2,6],[-1,2]])
a = Matrix([0,5])
x = F.inv() * a
x

Matrix([
[-3],
[ 1]])

Теорема Кронкера-Капелли:

rangA = rang(A|b) = n совместна, имеет 1 решение

rangA < rang(A\b) несовместна, нет решений

rangA = rang(A|b) < n бескон. кол-во решений

In [90]:
x1,x2,x3 = symbols('x1 x2 x3')

exp1 = Eq(x1 - 2 * x2 + 4 * x3, 6)
exp2 = Eq(x1 - 2 * x2 + x3, 4)
exp3 = Eq(-3 * x1 + 6 * x2 - 12 * x3, -18)

sys = [exp1, exp2, exp3]

solve = linsolve(sys, x1,x2,x3)
solve

{(2*x2 + 10/3, x2, 2/3)}